#!/usr/bin/env bash
# mb-search.sh — search within Memory Bank.
#
# Usage:
#   mb-search.sh <query> [mb_path]                     # full-text grep/rg
#   mb-search.sh --tag <tag> [mb_path]                 # filter by tag from index.json
#   mb-search.sh [--show-private] <query> [mb_path]    # show `<private>` content
#
# The `--tag` flag requires `.memory-bank/index.json` (generated by `mb-index-json.py`).
# If `index.json` is missing — warning + auto-regenerate attempt, otherwise exit 1.
#
# PII protection (Stage 3 v2.1):
#   `<private>...</private>` blocks in notes are replaced with `[REDACTED]` by default.
#   `--show-private` requires `MB_SHOW_PRIVATE=1` (double confirmation), otherwise exit 2.

set -euo pipefail

# shellcheck source=_lib.sh
source "$(dirname "$0")/_lib.sh"

# ═══ Parse flags ═══
SHOW_PRIVATE=0
INCLUDE_ARCHIVED=0
ARGS=()
END_OF_FLAGS=0
for arg in "$@"; do
  if [ "$END_OF_FLAGS" -eq 1 ]; then
    ARGS+=("$arg")
    continue
  fi
  case "$arg" in
    --)                 END_OF_FLAGS=1 ;;
    --show-private)     SHOW_PRIVATE=1 ;;
    --include-archived) INCLUDE_ARCHIVED=1 ;;
    *)                  ARGS+=("$arg") ;;
  esac
done

if [ "$SHOW_PRIVATE" -eq 1 ] && [ "${MB_SHOW_PRIVATE:-0}" != "1" ]; then
  echo "[error] --show-private requires MB_SHOW_PRIVATE=1 env (double confirmation)" >&2
  echo "[hint]  MB_SHOW_PRIVATE=1 mb-search --show-private <query>" >&2
  exit 2
fi

# If there are arguments after parsing, use them; otherwise original "$@" is empty.
if [ "${#ARGS[@]}" -gt 0 ]; then
  set -- "${ARGS[@]}"
else
  set --
fi

# ═══ REDACT filter for output ═══
# By default, strip `<private>...</private>` (inline and multi-line).
# For lines with an opening `<private>` without a closing tag on the same line, redact the whole line.
redact() {
  if [ "$SHOW_PRIVATE" -eq 1 ]; then
    cat
    return
  fi
  # Inline closed: <private>...</private> → [REDACTED]
  # Lines with <private> but no </private> on the same line → [REDACTED multi-line private]
  # Lines with </private> but no <private> on the same line (block tail) → [REDACTED multi-line private]
  awk '
    {
      line = $0
      has_open = index(line, "<private>")
      has_close = index(line, "</private>")
      if (has_open > 0 && has_close > 0 && has_close > has_open) {
        # closed inline → substitute contents.
        gsub(/<private>[^<]*<\/private>/, "[REDACTED]", line)
        print line
        next
      }
      if (has_open > 0 || has_close > 0) {
        print "[REDACTED — multi-line private]"
        in_block = (has_open > 0 && has_close == 0)
        if (has_close > 0) in_block = 0
        next
      }
      if (in_block) {
        print "[REDACTED — multi-line private]"
        next
      }
      print line
    }
  '
}

# ═══ Tag mode ═══
if [ "${1:-}" = "--tag" ]; then
  TAG="${2:?Usage: mb-search.sh --tag <tag> [mb_path]}"
  MB_PATH=$(mb_resolve_path "${3:-}")

  INDEX="$MB_PATH/index.json"
  if [ ! -f "$INDEX" ]; then
    if [ -x "$(dirname "$0")/mb-index-json.py" ]; then
      python3 "$(dirname "$0")/mb-index-json.py" "$MB_PATH" >/dev/null 2>&1 || true
    fi
  fi

  if [ ! -f "$INDEX" ]; then
    echo "[error] index.json not found: $INDEX" >&2
    echo "[hint]  generate it with: python3 $(dirname "$0")/mb-index-json.py $MB_PATH" >&2
    exit 1
  fi

  matches=$(TAG="$TAG" INDEX_PATH="$INDEX" INCLUDE_ARCHIVED="$INCLUDE_ARCHIVED" python3 -c "
import json, os
tag = os.environ['TAG']
include_archived = os.environ.get('INCLUDE_ARCHIVED') == '1'
with open(os.environ['INDEX_PATH']) as f: data = json.load(f)
for n in data.get('notes', []):
    if not include_archived and n.get('archived'):
        continue
    if tag in (n.get('tags') or []):
        print(n['path'])
")

  if [ -z "$matches" ]; then
    echo "Nothing found for tag: $TAG"
    exit 0
  fi

  echo "$matches" | while read -r rel; do
    [ -z "$rel" ] && continue
    echo "=== $rel ==="
    head -20 "$MB_PATH/$rel" 2>/dev/null | redact || true
    echo ""
  done
  exit 0
fi

# ═══ Freetext mode ═══
QUERY="${1:?Usage: mb-search.sh <query> [mb_path]  OR  mb-search.sh --tag <tag> [mb_path]}"
MB_PATH=$(mb_resolve_path "${2:-}")

if [[ ! -d "$MB_PATH" ]]; then
  echo "[MEMORY BANK: INACTIVE] Directory $MB_PATH not found" >&2
  exit 1
fi

if [ "$SHOW_PRIVATE" -eq 1 ]; then
  # Full output (the user explicitly confirmed through MB_SHOW_PRIVATE=1).
  # `notes/archive/` is still excluded unless `--include-archived` is used.
  EXCLUDE_ARCHIVE=$([ "$INCLUDE_ARCHIVED" -eq 1 ] && echo "" || echo "notes/archive")
  # `--` ends rg/grep flag parsing so a query that starts with `-` is treated
  # as a search term rather than an unknown option.
  if command -v rg >/dev/null 2>&1; then
    if [ -n "$EXCLUDE_ARCHIVE" ]; then
      rg --color=never -n -i --type md --heading -g '!notes/archive/**' -e "$QUERY" -- "$MB_PATH" 2>/dev/null \
        || echo "Nothing found for query: $QUERY"
    else
      rg --color=never -n -i --type md --heading -e "$QUERY" -- "$MB_PATH" 2>/dev/null \
        || echo "Nothing found for query: $QUERY"
    fi
  else
    if [ -n "$EXCLUDE_ARCHIVE" ]; then
      grep -rn -i --include="*.md" --exclude-dir="archive" -e "$QUERY" -- "$MB_PATH" 2>/dev/null \
        || echo "Nothing found for query: $QUERY"
    else
      grep -rn -i --include="*.md" -e "$QUERY" -- "$MB_PATH" 2>/dev/null \
        || echo "Nothing found for query: $QUERY"
    fi
  fi
else
  # Safe mode: annotate private spans and redact hits inside those spans.
  QUERY="$QUERY" MB="$MB_PATH" INCLUDE_ARCHIVED="$INCLUDE_ARCHIVED" python3 - <<'PYEOF'
import os, re
from pathlib import Path

query = os.environ["QUERY"].lower()
mb = Path(os.environ["MB"])
include_archived = os.environ.get("INCLUDE_ARCHIVED") == "1"
priv_closed = re.compile(r"<private>.*?</private>", re.DOTALL)
priv_open = re.compile(r"<private>.*\Z", re.DOTALL)

REDACTED_STUB = "[REDACTED match in private block]"

found = False
for md in sorted(mb.rglob("*.md")):
    rel = md.relative_to(mb).as_posix()
    if not include_archived and rel.startswith("notes/archive/"):
        continue
    try:
        text = md.read_text(encoding="utf-8")
    except (OSError, UnicodeDecodeError):
        continue

    # Spans of all private blocks (closed and open).
    spans = [m.span() for m in priv_closed.finditer(text)]
    for m in priv_open.finditer(text):
        spans.append(m.span())

    lines = text.splitlines()
    hits = []
    offset = 0
    for i, line in enumerate(lines, 1):
        line_start = offset
        offset += len(line) + 1  # +1 for \n

        if query not in line.lower():
            continue

        # Line contains an opening/closing fence — inline private.
        if "<private>" in line or "</private>" in line:
            display = priv_closed.sub("[REDACTED]", line)
            if "<private>" in display or "</private>" in display:
                display = REDACTED_STUB
            hits.append((i, display))
        # Line is inside fences (multi-line block).
        elif any(s <= line_start < e for s, e in spans):
            hits.append((i, REDACTED_STUB))
        else:
            hits.append((i, line))

    if hits:
        found = True
        print(f"=== {rel} ===")
        for num, line in hits[:20]:
            print(f"{num}:{line}")
        print()

if not found:
    print(f"Nothing found for query: {os.environ['QUERY']}")
PYEOF
fi
