#!/usr/bin/env bash
# mb-traceability-gen.sh — regenerate traceability.md from specs + plans + tests.
#
# Usage: mb-traceability-gen.sh [mb_path]
#
# Scans:
#   .memory-bank/specs/*/requirements.md  — REQ-NNN definitions
#   .memory-bank/specs/*/tasks.md         — mb-task markers (via mb_work_items.py)
#   .memory-bank/plans/*.md + plans/done/*.md — covers_requirements frontmatter
#                                              + `<!-- covers: REQ-NNN -->` markers
#   tests/ (project root) AND mb_path/tests/ — grep for `REQ_NNN` substrings
#
# Writes: .memory-bank/traceability.md (full regeneration; idempotent).

set -euo pipefail

# shellcheck source=_lib.sh
source "$(dirname "$0")/_lib.sh"

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"

MB_PATH=$(mb_resolve_path "${1:-}")
[ -d "$MB_PATH" ] || { echo "[error] .memory-bank not found at: $MB_PATH" >&2; exit 1; }

MB_WORK_ITEMS="$SCRIPT_DIR/mb_work_items.py" python3 - "$MB_PATH" <<'PY'
import json
import os
import re
import subprocess
import sys
from pathlib import Path

mb = Path(sys.argv[1])
specs_dir = mb / "specs"
plans_dir = mb / "plans"
out_path = mb / "traceability.md"

mb_work_items_path = os.environ.get("MB_WORK_ITEMS", "")

REQ_RE = re.compile(r"\bREQ-(\d{3,})\b")
REQ_TEST_RE = re.compile(r"REQ_(\d{3,})")

# T5: handle no-specs state
if not specs_dir.is_dir() or not any(specs_dir.glob("*/requirements.md")):
    out_path.write_text(
        "# Traceability Matrix\n\n"
        "_Autogenerated by mb-traceability-gen.sh. Do not edit manually._\n\n"
        "No specs yet — run `/mb sdd <topic>` to create requirements.\n",
        encoding="utf-8",
    )
    print("[traceability-gen] no specs — minimal output written")
    sys.exit(0)

# T1: collect REQs from each spec
reqs: dict[str, dict] = {}
for req_file in sorted(specs_dir.glob("*/requirements.md")):
    spec_name = req_file.parent.name
    spec_rel = f"specs/{spec_name}/requirements.md"
    text = req_file.read_text(encoding="utf-8")
    for m in REQ_RE.finditer(text):
        req_id = f"REQ-{m.group(1)}"
        if req_id in reqs and reqs[req_id]["spec"] != spec_rel:
            print(
                f"[warn] {req_id} defined in multiple specs: "
                f"{reqs[req_id]['spec']} and {spec_rel}",
                file=sys.stderr,
            )
            continue
        reqs.setdefault(
            req_id,
            {"spec": spec_rel, "spec_tasks": [], "planned": "", "tests": ""},
        )


def parse_list(raw: str) -> list[str]:
    raw = raw.strip()
    if not (raw.startswith("[") and raw.endswith("]")):
        return []
    inner = raw[1:-1].strip()
    if not inner:
        return []
    return [item.strip().strip('"\'') for item in inner.split(",") if item.strip()]


FRONTMATTER_RE = re.compile(r"^---\s*\n(.*?)\n---\s*\n", re.DOTALL)
COVERS_MARKER_RE = re.compile(r"<!--\s*covers:\s*(.+?)\s*-->")


def plan_paths() -> list[Path]:
    out: list[Path] = []
    for p in sorted(plans_dir.glob("*.md")):
        out.append(p)
    done = plans_dir / "done"
    if done.is_dir():
        for p in sorted(done.glob("*.md")):
            out.append(p)
    return out


# T2: collect plan coverage
for plan in plan_paths():
    text = plan.read_text(encoding="utf-8")
    covered: set[str] = set()
    fm = FRONTMATTER_RE.match(text)
    if fm:
        for line in fm.group(1).splitlines():
            if line.strip().startswith("covers_requirements:"):
                _, _, v = line.partition(":")
                covered.update(parse_list(v))
    for m in COVERS_MARKER_RE.finditer(text):
        for item in m.group(1).split(","):
            item = item.strip()
            if REQ_RE.fullmatch(item):
                covered.add(item)
    if not covered:
        continue
    rel = plan.relative_to(mb).as_posix()
    for req in covered:
        if req in reqs:
            existing = reqs[req]["planned"]
            reqs[req]["planned"] = (existing + " " if existing else "") + rel

# T2.5: scan specs/*/tasks.md via mb_work_items.py
if mb_work_items_path and Path(mb_work_items_path).is_file():
    for tasks_file in sorted(specs_dir.glob("*/tasks.md")):
        spec_topic = tasks_file.parent.name
        proc = subprocess.run(
            ["python3", mb_work_items_path, str(tasks_file)],
            capture_output=True,
            text=True,
            check=False,
        )
        if proc.returncode != 0:
            print(
                f"[warn] mb_work_items.py failed for {tasks_file}: {proc.stderr.strip()}",
                file=sys.stderr,
            )
            continue
        for line in proc.stdout.splitlines():
            line = line.strip()
            if not line:
                continue
            try:
                item = json.loads(line)
            except json.JSONDecodeError:
                continue
            for req_id in item.get("covers", []):
                req_id = req_id.upper()
                if req_id in reqs:
                    reqs[req_id]["spec_tasks"].append(
                        (spec_topic, item["item_no"])
                    )

# T3: grep tests at repo-root/tests and mb/tests
test_roots = [mb.parent / "tests", mb / "tests"]
for root in test_roots:
    if not root.is_dir():
        continue
    for tf in root.rglob("*"):
        if not tf.is_file():
            continue
        if tf.suffix not in {".py", ".ts", ".tsx", ".js", ".go", ".rs", ".sh"}:
            continue
        try:
            content = tf.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        hits: set[str] = set()
        for m in REQ_RE.finditer(content):
            hits.add(f"REQ-{m.group(1)}")
        for m in REQ_TEST_RE.finditer(content):
            hits.add(f"REQ-{m.group(1)}")
        if not hits:
            continue
        rel = tf.relative_to(mb.parent if root == mb.parent / "tests" else mb).as_posix()
        for req in hits:
            if req in reqs:
                existing = reqs[req]["tests"]
                reqs[req]["tests"] = (existing + " " if existing else "") + rel

# Compose output
total = len(reqs)
planned = sum(1 for r in reqs.values() if r["planned"])
tested = sum(1 for r in reqs.values() if r["tests"])
tasks_covered = sum(1 for r in reqs.values() if r["spec_tasks"])


def _spec_task_cell(spec_tasks: list) -> str:
    if not spec_tasks:
        return "—"
    # Sort for idempotency, deduplicate
    seen: set[tuple] = set()
    unique = []
    for t in spec_tasks:
        key = (t[0], t[1])
        if key not in seen:
            seen.add(key)
            unique.append(t)
    unique.sort(key=lambda t: (t[0], t[1]))
    refs = [f"specs/{topic}/tasks.md#task-{no}" for topic, no in unique]
    return ", ".join(refs)


def status_for(r: dict) -> str:
    has_coverage = bool(r["spec_tasks"] or r["planned"])
    has_tests = bool(r["tests"])
    if has_coverage and has_tests:
        return "✅"
    if has_coverage:
        return "🏗️"
    return "⬜"


rows = []
for req_id in sorted(reqs):
    r = reqs[req_id]
    spec_task_cell = _spec_task_cell(r["spec_tasks"])
    rows.append(
        f"| {req_id} | {r['spec']} | {spec_task_cell} "
        f"| {r['planned'] or '—'} | {r['tests'] or '—'} | {status_for(r)} |"
    )

orphans = [
    req_id
    for req_id, r in sorted(reqs.items())
    if not r["spec_tasks"] and not r["planned"]
]

body = [
    "# Traceability Matrix",
    "",
    "_Autogenerated by mb-traceability-gen.sh. Do not edit manually._",
    "",
    "## Coverage",
    f"- Total REQs: {total}",
    f"- Planned: {planned}",
    f"- Tested: {tested}",
    f"- Tasks-covered: {tasks_covered}",
    "",
    "## Matrix",
    "",
    "| REQ | Spec | Spec Task | Plan / Stage | Tests | Status |",
    "|-----|------|-----------|--------------|-------|--------|",
]
body.extend(rows if rows else ["| _no REQs_ | — | — | — | — | — |"])

body.extend(
    [
        "",
        "## Orphans",
        "",
        *(
            [f"- {req} — in spec but no covering plan or task" for req in orphans]
            if orphans
            else ["_None._"]
        ),
        "",
    ]
)

out_path.write_text("\n".join(body), encoding="utf-8")
print(
    f"[traceability-gen] total={total} planned={planned} "
    f"tested={tested} tasks_covered={tasks_covered} orphans={len(orphans)}"
)
PY
