"""Contract tests for mb-traceability-gen.sh.

Public contract:
  T1. Scan `.memory-bank/specs/*/requirements.md` for REQ-NNN definitions
      (first `- REQ-NNN:` or `### REQ-NNN` — either form)
  T2. Scan `.memory-bank/plans/*.md` AND `plans/done/*.md` for `covers_requirements:`
      frontmatter or `<!-- covers: REQ-NNN[, REQ-NNN] -->` inline markers
  T3. Scan `tests/` (if present at repo root OR at `mb_path/tests/`) for `REQ_NNN`
      substrings in file content — treat those tests as covering the REQ
  T4. Produce `.memory-bank/traceability.md` with:
        - `_Autogenerated by mb-traceability-gen.sh. Do not edit manually._` header
        - Coverage summary (Total REQs / Planned / Tested)
        - Matrix table | REQ | Spec | Plan / Stage | Tests | Status |
        - Orphans section for REQs without plan OR tests without REQ link (best-effort)
  T5. If no specs directory exists, produce a minimal `traceability.md` that says
      "No specs yet — run /mb sdd <topic> to create requirements." and exit 0
  T6. Idempotent
"""

from __future__ import annotations

import subprocess
from pathlib import Path
from textwrap import dedent

REPO_ROOT = Path(__file__).resolve().parents[2]
SCRIPT = REPO_ROOT / "scripts" / "mb-traceability-gen.sh"


def _init_mb(tmp_path: Path, *, with_specs: bool = True) -> Path:
    mb = tmp_path / ".memory-bank"
    mb.mkdir()
    (mb / "plans").mkdir()
    (mb / "plans" / "done").mkdir()
    (mb / "checklist.md").write_text("# Checklist\n", encoding="utf-8")
    (mb / "roadmap.md").write_text("# Roadmap\n", encoding="utf-8")
    if with_specs:
        (mb / "specs").mkdir()
        (mb / "specs" / "demo").mkdir()
        (mb / "specs" / "demo" / "requirements.md").write_text(
            dedent("""\
                # demo requirements

                - REQ-001: The system must X.
                - REQ-002: When Y, the system shall Z.
                - REQ-003: The system must W.
                """),
            encoding="utf-8",
        )
    return mb


def _run(mb: Path) -> subprocess.CompletedProcess[str]:
    return subprocess.run(
        ["bash", str(SCRIPT), str(mb)],
        capture_output=True,
        text=True,
        check=False,
    )


def test_contract_t1_t4_basic_matrix(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path)
    # Plan with frontmatter covers + one inline marker
    (mb / "plans" / "2026-04-22_feature_demo.md").write_text(
        dedent("""\
            ---
            type: feature
            topic: demo
            status: in_progress
            depends_on: []
            parallel_safe: false
            linked_specs: [specs/demo]
            sprint: 1
            phase_of: demo
            created: 2026-04-22
            covers_requirements: [REQ-001, REQ-002]
            ---

            # Plan: demo

            ## Task 1: First

            <!-- covers: REQ-003 -->
            - [ ] Step 1
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    assert "Autogenerated by mb-traceability-gen.sh" in trace
    assert "REQ-001" in trace
    assert "REQ-002" in trace
    assert "REQ-003" in trace
    assert "## Coverage" in trace
    assert "Total REQs: 3" in trace

    # I2: structural assertion — extract Matrix section and verify each REQ's
    # Plan/Stage column points to the plan file. Substring-only checks
    # previously missed cases where a REQ appeared elsewhere in the doc
    # but had an empty Plan column.
    # NOTE: Stage 2 added Spec Task column — schema is now 6 columns:
    #   REQ | Spec | Spec Task | Plan / Stage | Tests | Status
    matrix_section = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]
    expected_plan = "plans/2026-04-22_feature_demo.md"
    for req_id in ("REQ-001", "REQ-002", "REQ-003"):
        rows = [
            line for line in matrix_section.splitlines()
            if line.startswith(f"| {req_id} |")
        ]
        assert len(rows) == 1, f"expected one matrix row for {req_id}, got: {rows}"
        cells = [c.strip() for c in rows[0].strip().strip("|").split("|")]
        assert len(cells) == 6, f"expected 6 columns for {req_id}, got {len(cells)}: {cells}"
        plan_cell = cells[3]
        assert expected_plan in plan_cell, (
            f"{req_id} Plan/Stage cell must reference {expected_plan}, got: {plan_cell!r}"
        )


def test_contract_t5_no_specs(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path, with_specs=False)
    result = _run(mb)
    assert result.returncode == 0, result.stderr
    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    assert "No specs yet" in trace


def test_contract_t6_idempotent(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path)
    first = _run(mb)
    assert first.returncode == 0, first.stderr
    after_first = (mb / "traceability.md").read_text(encoding="utf-8")

    second = _run(mb)
    assert second.returncode == 0, second.stderr
    after_second = (mb / "traceability.md").read_text(encoding="utf-8")
    assert after_first == after_second


def test_orphan_detection(tmp_path: Path) -> None:
    mb = _init_mb(tmp_path)
    # Plan covers only REQ-001 — REQ-002 and REQ-003 become orphans
    (mb / "plans" / "2026-04-22_feature_partial.md").write_text(
        dedent("""\
            ---
            type: feature
            topic: partial
            status: in_progress
            depends_on: []
            parallel_safe: false
            linked_specs: [specs/demo]
            sprint: 1
            phase_of: demo
            created: 2026-04-22
            covers_requirements: [REQ-001]
            ---

            # Plan: partial

            ## Task 1: First
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    assert "## Orphans" in trace
    orphans_section = trace.split("## Orphans")[1]
    # REQ-002 and REQ-003 uncovered → should appear in orphan list
    assert "REQ-002" in orphans_section
    assert "REQ-003" in orphans_section
    # I3: REQ-001 is covered by the plan → must NOT appear as an orphan
    assert "REQ-001" not in orphans_section, (
        "REQ-001 is covered by plan frontmatter — must not appear in Orphans section"
    )


def test_marker_only_path(tmp_path: Path) -> None:
    """REG-C1: `<!-- covers: REQ-NNN -->` marker alone (no frontmatter) must mark
    the REQ as covered. Previously the regex `[^-]+?` excluded hyphens, so every
    valid REQ ID (which contains `-`) failed to match — dead code path.
    """
    mb = _init_mb(tmp_path)
    # Plan uses ONLY inline marker — no frontmatter covers_requirements
    (mb / "plans" / "2026-04-22_feature_marker_only.md").write_text(
        dedent("""\
            # Plan: marker only

            ## Task 1

            <!-- covers: REQ-001 -->
            - [ ] Step 1
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    # Matrix section: extract row for REQ-001 and verify Plan column is non-empty
    matrix_section = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]
    req001_rows = [
        line for line in matrix_section.splitlines()
        if line.startswith("| REQ-001 |")
    ]
    assert len(req001_rows) == 1, f"expected one matrix row for REQ-001, got: {req001_rows}"
    row = req001_rows[0]
    # Structure (Stage 2): | REQ-001 | spec | Spec Task | plan | tests | status |
    cells = [c.strip() for c in row.strip().strip("|").split("|")]
    assert len(cells) == 6, f"expected 6 columns, got {len(cells)}: {cells}"
    plan_cell = cells[3]
    assert plan_cell != "—", f"Plan/Stage column must be non-empty for marker-covered REQ-001, got: {plan_cell!r}"
    assert "marker_only" in plan_cell, f"expected plan filename in Plan cell, got: {plan_cell!r}"

    # Also: REQ-001 must NOT appear in orphans section
    orphans_section = trace.split("## Orphans", 1)[1]
    assert "REQ-001" not in orphans_section, "REQ-001 is marker-covered — must not be orphan"


def test_duplicate_req_across_specs_emits_warning(tmp_path: Path) -> None:
    """If REQ-001 is defined in two specs, stderr must carry a collision warning."""
    mb = _init_mb(tmp_path)  # creates specs/demo/requirements.md with REQ-001..003
    (mb / "specs" / "other").mkdir()
    (mb / "specs" / "other" / "requirements.md").write_text(
        "# other spec\n\n- REQ-001: Duplicate of demo's REQ-001.\n",
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr
    assert "REQ-001" in result.stderr
    assert "multiple specs" in result.stderr or "defined in" in result.stderr


def test_pytest_naming_convention(tmp_path: Path) -> None:
    """REG-C2: tests following pytest convention `def test_REQ_NNN_...():` must be
    detected. Previously `\\b` around `REQ_` failed because `_` is a word char in
    Python regex, so `test_REQ_001` had no boundary before `R`.
    """
    mb = _init_mb(tmp_path)
    # No plan coverage — only test file
    tests_root = mb / "tests" / "unit"
    tests_root.mkdir(parents=True)
    (tests_root / "test_foo.py").write_text(
        "def test_REQ_001_works():\n    pass\n",
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    matrix_section = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]
    req001_rows = [
        line for line in matrix_section.splitlines()
        if line.startswith("| REQ-001 |")
    ]
    assert len(req001_rows) == 1, f"expected one matrix row for REQ-001, got: {req001_rows}"
    row = req001_rows[0]
    # Structure (Stage 2): | REQ-001 | spec | Spec Task | plan | tests | status |
    cells = [c.strip() for c in row.strip().strip("|").split("|")]
    assert len(cells) == 6, f"expected 6 columns, got {len(cells)}: {cells}"
    tests_cell = cells[4]
    assert tests_cell != "—", f"Tests column must be non-empty when test_REQ_001_* exists, got: {tests_cell!r}"
    assert "test_foo.py" in tests_cell, f"expected test filename in Tests cell, got: {tests_cell!r}"


def test_traceability_gen_still_handles_plan_only_repos(tmp_path: Path) -> None:
    """REG-C3: repo with plan coverage but no specs/tasks.md must still generate
    traceability with `—` in the Spec Task column for every row.

    This locks the Stage 2 backward-compat contract: the Spec Task column is
    always present in the matrix, even when no tasks.md files exist.
    """
    mb = _init_mb(tmp_path)
    # Plan covers all three REQs via frontmatter; no tasks.md exists
    (mb / "plans" / "2026-04-22_feature_plan_only.md").write_text(
        dedent("""\
            ---
            type: feature
            topic: plan_only
            status: in_progress
            depends_on: []
            parallel_safe: false
            linked_specs: []
            sprint: 1
            phase_of: demo
            created: 2026-04-22
            covers_requirements: [REQ-001, REQ-002, REQ-003]
            ---

            # Plan: plan only — no tasks.md

            ## Stage 1: implement everything

            <!-- mb-stage:1 -->
            - [ ] Step 1
            """),
        encoding="utf-8",
    )

    result = _run(mb)
    assert result.returncode == 0, result.stderr

    trace = (mb / "traceability.md").read_text(encoding="utf-8")
    matrix_section = trace.split("## Matrix", 1)[1].split("## Orphans", 1)[0]

    # Header must include Spec Task column
    header_line = next(
        (ln for ln in matrix_section.splitlines() if ln.startswith("|")),
        "",
    )
    assert "Spec Task" in header_line, (
        f"Matrix header must contain 'Spec Task' column even for plan-only repos, "
        f"got: {header_line!r}"
    )

    # Every REQ row must have — in the Spec Task column (index 2)
    for req_id in ("REQ-001", "REQ-002", "REQ-003"):
        rows = [
            line for line in matrix_section.splitlines()
            if line.startswith(f"| {req_id} |")
        ]
        assert len(rows) == 1, f"expected one matrix row for {req_id}, got: {rows}"
        cells = [c.strip() for c in rows[0].strip().strip("|").split("|")]
        # New column order: REQ | Spec | Spec Task | Plan / Stage | Tests | Status
        assert len(cells) == 6, (
            f"expected 6 columns (with Spec Task) for {req_id}, got {len(cells)}: {cells}"
        )
        spec_task_cell = cells[2]
        assert spec_task_cell == "—", (
            f"{req_id} Spec Task cell must be '—' when no tasks.md exists, "
            f"got: {spec_task_cell!r}"
        )
